### ISSUE TITLE
firefox issue for input elements inside of dnd-draggable

### ISSUE THREAD

**Issue by ayaniv** [marceljuenemann/angular-drag-and-drop-lists#199] opened 2016-01-24 15:27 UTC
cant select text inside input texts in Firefox.
also, cant use mouse to place the cursor in specific place inside the input element.

try to select text with your mouse using FF in the following link:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types

**Comment by gummdy** [comment] 2016-01-29 21:01
This is the same core problem talked about in issue #127

**Comment by marceljuenemann** [comment] 2016-01-31 13:55
Duplicate of #127

**Closed by marceljuenemann** 2016-01-31 13:55 UTC
