### ISSUE TITLE
ignore list for element you want drag in side a drag drop container 

### ISSUE THREAD

**Issue by redyyu** [marceljuenemann/angular-drag-and-drop-lists#74] opened 2015-06-06 16:40 UTC
etc., A input might in side drag container but when you point intro input filed you wont trigger drag.
can you add some attribute for child element skip drag drop.

**Comment by marceljuenemann** [comment] 2015-07-10 00:43
Can you try setting pointer-events: none in CSS?

**Comment by redyyu** [comment] 2015-07-10 01:44
No I can't. That will break other js frameworks events flow. Etc., angular material.

**Comment by marceljuenemann** [comment] 2015-07-23 09:29
Duplicate of #57, will be fixed in next release

**Closed by marceljuenemann** 2015-07-23 09:29 UTC

**Comment by redyyu** [comment] 2015-07-23 10:39
Thank you very much, can wait. :)
