### ISSUE TITLE
Angular2

### ISSUE THREAD

**Issue by jimitndiaye** [marceljuenemann/angular-drag-and-drop-lists#269] opened 2016-05-25 14:33 UTC
I just came across this awesome library, particularly [this](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested) demo. Unfortunately I'm working within an Angular2 app and thus I'm hoping it can be (or, hopefully, has been) ported to Angular 2. If no such effort currently exists then I'd be very interested in initiating it, with your assistance.

**Comment by krasevych** [comment] 2016-06-01 14:38
the same situation.
Will you adapt the library to angular 2?

**Comment by marceljuenemann** [comment] 2016-06-07 22:53
Duplicate of #229 

I was nearly done with a new version of this library (see dev branch), once I get around to finishing that, I'll do an angular2 version. Please don't wait for me though, I don't maintain this directive very regularly.

**Closed by marceljuenemann** 2016-06-07 22:53 UTC

**Comment by Bhushan001** [comment] 2016-10-07 10:43
@marceljuenemann any inputs on this yet, I require such feature in my app.thanks

**Comment by karol-depka** [comment] 2017-03-06 17:12
+1. Nice work. Would be nice to have this for Angular 2. If it comes to that, I hope to be able to contribute.
