### ISSUE TITLE
Control for Angular 2

### ISSUE THREAD

**Issue by imilic1** [marceljuenemann/angular-drag-and-drop-lists#296] opened 2016-07-16 13:51 UTC
Hi Marcel,
First of all, thank you for this amazing dnd solution.
This is kind of question / feature request - Is there going to be a version for Angular 2 and when if planned?

Regards
Ivan

**Comment by raimund-schluessler** [comment] 2017-01-16 12:34
Duplicate of #229 ?

**Comment by marceljuenemann** [comment] 2017-01-17 00:07
Duplicate of #229.

**Closed by marceljuenemann** 2017-01-17 00:07 UTC
