### ISSUE TITLE
Not able to edit textbox within a draggable item: Only in IE

### ISSUE THREAD

**Issue by sreekumarp** [marceljuenemann/angular-drag-and-drop-lists#191] opened 2015-12-22 11:10 UTC
In IE (tried in IE 11),
Not able to type anything in textbox if the textbox is inside draggable item

Try this url in IE 11:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types

**Comment by gummdy** [comment] 2016-01-21 16:52
this is a duplicate of #127

**Comment by marceljuenemann** [comment] 2016-01-31 14:16
What gummdy said, I'll have to take a look at #127

**Closed by marceljuenemann** 2016-01-31 14:16 UTC
