### ISSUE TITLE
dndDragging class not applied to ghost image on OSX Chrome / Firefox

### ISSUE THREAD

**Issue by techsoldaten** [marceljuenemann/angular-drag-and-drop-lists#212] opened 2016-02-15 09:26 UTC
With the latest version of angular-drag-and-drop lists (1.4.0), the dndDragging class does not appear to be added to the ghost image of elements while dragging. The class does get applied to the original element, but not the one seen while dragging. 

Here's the code:

    <div
      ng-repeat="task in vm.project.tasks | filter: { storyid: story.nid }  | filter: { status: state }" 
      class="some-element"
      dnd-draggable="some-element" 
      dnd-effect-allowed="move" 
      dnd-type="some-element">
        ... some content here
    </div>

And the CSS:

    .dndDragging {
      transform:rotate(-7deg) !important; 
      background-color: Red !important;
    }

The result is that the background color and transform are added to the original element, but not the one seen while dragging.

This is happening on OSX with Chrome Version 48.0.2564.109 (64-bit) and Firefox 29.0. I haven't tested this on Windows or other browsers.

**Comment by marceljuenemann** [comment] 2016-02-15 09:35
Works for me. When I modify this demo http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested as follows, then I can see the changes while dragging.

```
.nestedDemo .dropzone .dndDragging {
    background-color: red;
    transform: rotate(-7deg);
}
```

**Comment by techsoldaten** [comment] 2016-02-15 10:49
Thank you for the quick reply. Awesome, I will grab a copy of the demos and check them on my local.

Any thoughts on what else could be causing the issue? The one other thing to point out is elements do become transparent when I drag them. I grepped the CSS for my app and there are no other styles associated with .dndDragging that exist.

**Comment by techsoldaten** [comment] 2016-02-15 22:01
The demo works fine on my local machine, but it still doesn't work in my app.

Not sure how to debug this. My code is not very different from the demo.

The app and the demo have the same doctype. I see where dndDragging is added on dragstart and looked for other event listeners in the code inspector. There aren't any others, so I don't think that's the issue. There are no errors in the console when I run it, so that's not the issue either.

Any help would be appreciated, and thank you for this wonderful module.

**Comment by marceljuenemann** [comment] 2016-02-20 15:15
Closing as this is not a bug in the directive apparently.

Hard to say where your problem is without seeing the code, probably something wrong with your CSS?

**Closed by marceljuenemann** 2016-02-20 15:15 UTC

**Comment by techsoldaten** [comment] 2016-02-20 16:47
The CSS applies correctly to the original object, just not the ghost image. I am thinking it has to do with something else setting methods on the html5 drag and drop object, but I don't know exactly what to check for.

**Comment by techsoldaten** [comment] 2016-02-27 22:12
I finally solved this. 

The problem was with the CSS, specifically with transforms and pseudo-classes. The element I was trying to drag had a :hover class that changed the background color. There was also a CSS transition of ease-in at .2 seconds.

Transitions appear to kill dnd-draggable. They stops immediately once the element is being dragged without the classes being applied. I think the solution is to remove any transitions from the source element.

**Comment by amonsot890** [comment] 2017-05-17 03:12
hi, i have this kind of problem too. help me fix this please.

transform : rotate(9deg) is not working on dndDragging class.

**Comment by Alagappapandian** [comment] 2017-11-10 15:37
I found one Solution. maintain draggabe element width less the 300px. [ http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested ]( http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested ) demo size is less then 300px, if u change  the width >= 300 px drag element become ghost image.
