### ISSUE TITLE
'copy' property works in FF but not safari.

### ISSUE THREAD

**Issue by alexliubj** [marceljuenemann/angular-drag-and-drop-lists#105] opened 2015-07-29 19:37 UTC
If i set copy for the list, it still does 'move'
Delete from the original list.

**Comment by alexliubj** [comment] 2015-07-30 13:03
Which I mean it is still doing 'move' but not 'copy' in safari.

<li ng-repeat="item in list"
        dnd-draggable="item"
        dnd-moved="list.splice($index, 1)"
        dnd-effect-allowed="copy"
        dnd-selected="models.selected = item"
        ng-class="{'selected': models.selected === item}"
        >
      <label>{{item.label}}</label>
    </li>

**Comment by alexliubj** [comment] 2015-07-30 13:07
Works well in FF and Chrome but no safari Version 8.0.7 (10600.7.12)

**Comment by marceljuenemann** [comment] 2015-08-21 00:12
Was able to reproduce this.

As a workaround, you can perform the same action on dnd-moved as you do for dnd-copied, since dnd-moved should never be called if you set dnd-effect-allowed to copy.

**Comment by marceljuenemann** [comment] 2017-01-16 00:03
This is fixed with 2.1.0. There is a design document in the Wiki with some background info on the fix. Note that this does not work in Safari across browser tabs if you intend to use dnd-external-sources.

**Closed by marceljuenemann** 2017-01-16 00:03 UTC
Labels: bug
