### ISSUE TITLE
Placeholder not dissapearing after drag and drop in FF (v.39)

### ISSUE THREAD

**Issue by hyukchan** [marceljuenemann/angular-drag-and-drop-lists#103] opened 2015-07-29 13:08 UTC
When we drag and drop the last element of the list, sometimes the placeholder does not dissapear.

It seems that it happens when the placeholder is smaller than the elements of the list.
Click on the very bottom of the element to start drag,
than while dragging move the mouse to the bottom. A placeholder appears and when we drop the element outside of the placeholder, the placeholder does not dissapear...

This problem doesn't occur with Chrome (V.43) though

**Comment by marceljuenemann** [comment] 2015-08-20 23:48
I tried to reproduce this with FF 39 on Ubuntu, but had no success so far. Are you using one of the demos?

**Comment by marceljuenemann** [comment] 2015-08-21 10:10
This should only be possible if a dragover event is fired after a dragleave, which would be a browser bug. But I might be wrong.

**Comment by valtersboze** [comment] 2015-12-22 21:48
getting same problem. im adding bgcolor like .dndDragover {  background: red; }, using fixed visual slots. if i drag an item away from slot, the dndDragover class still stays in previous (now empty) slot, thus leaving bgcolor for the slot.
this happens only in Firefox, using Linux Mint. Using Firefox with Wine emulator is the same, so its FF only. cant reproduce on the demos though.

**Comment by marceljuenemann** [comment] 2016-02-01 20:52
Will experiment with a different dragleave logic for v2

**Comment by marceljuenemann** [comment] 2016-12-25 16:25
WIll mark as duplicate of #119, as having a different dragleave algorithm would probably fix this.

**Closed by marceljuenemann** 2016-12-25 16:25 UTC
