### ISSUE TITLE
dndDragover class is added/removed repeatedly on dragenter of child

### ISSUE THREAD

**Issue by mcMickJuice** [marceljuenemann/angular-drag-and-drop-lists#318] opened 2016-09-01 21:41 UTC
When dragging element of a dropzone's child element, dragleave is fired even though dragovers continue to fire on dropzone element.  We use this class to style our dropzone element and it's causing the styling to flicker.
#317 fixes this issue using debounce and on resolution of the debounce method, both dndDragover class and the placeholder are removed.

**Comment by mcMickJuice** [comment] 2016-12-19 21:44
hi @marceljuenemann would you be able to review this pending PR and merge when you get a chance? Thanks!

**Comment by marceljuenemann** [comment] 2016-12-25 16:55
Already experimented with a new dragleave handler, but need to give it another attempt: Duplicate of #119

**Closed by marceljuenemann** 2016-12-25 16:55 UTC
